package com.jesusdmedinac.compose.sdui.presentation.screenmodel

import com.jesusdmedinac.jsontocompose.model.NodeProperties

interface NodePropertiesVisitor<T> {
    fun visit(props: NodeProperties.AlertDialogProps): T = visitDefault(props)
    fun visit(props: NodeProperties.BadgeProps): T = visitDefault(props)
    fun visit(props: NodeProperties.BadgedBoxProps): T = visitDefault(props)
    fun visit(props: NodeProperties.BottomBarProps): T = visitDefault(props)
    fun visit(props: NodeProperties.BottomNavigationItemProps): T = visitDefault(props)
    fun visit(props: NodeProperties.BoxProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ButtonProps): T = visitDefault(props)
    fun visit(props: NodeProperties.CardProps): T = visitDefault(props)
    fun visit(props: NodeProperties.CheckboxProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ChipProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ColumnProps): T = visitDefault(props)
    fun visit(props: NodeProperties.CustomProps): T = visitDefault(props)
    fun visit(props: NodeProperties.DatePickerProps): T = visitDefault(props)
    fun visit(props: NodeProperties.DividerProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ExtendedFabProps): T = visitDefault(props)
    fun visit(props: NodeProperties.FabProps): T = visitDefault(props)
    fun visit(props: NodeProperties.FilterChipProps): T = visitDefault(props)
    fun visit(props: NodeProperties.FlowColumnProps): T = visitDefault(props)
    fun visit(props: NodeProperties.FlowRowProps): T = visitDefault(props)
    fun visit(props: NodeProperties.IconProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ImageProps): T = visitDefault(props)
    fun visit(props: NodeProperties.InputChipProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ListItemProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ModalBottomSheetProps): T = visitDefault(props)
    fun visit(props: NodeProperties.NavigationBarItemProps): T = visitDefault(props)
    fun visit(props: NodeProperties.NavigationBarProps): T = visitDefault(props)
    fun visit(props: NodeProperties.NavigationDrawerItemProps): T = visitDefault(props)
    fun visit(props: NodeProperties.NavigationDrawerProps): T = visitDefault(props)
    fun visit(props: NodeProperties.NavigationRailItemProps): T = visitDefault(props)
    fun visit(props: NodeProperties.NavigationRailProps): T = visitDefault(props)
    fun visit(props: NodeProperties.OutlinedCardProps): T = visitDefault(props)
    fun visit(props: NodeProperties.PagerProps): T = visitDefault(props)
    fun visit(props: NodeProperties.PlainTooltipProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ProgressIndicatorProps): T = visitDefault(props)
    fun visit(props: NodeProperties.RadioButtonProps): T = visitDefault(props)
    fun visit(props: NodeProperties.RichTooltipProps): T = visitDefault(props)
    fun visit(props: NodeProperties.RowProps): T = visitDefault(props)
    fun visit(props: NodeProperties.ScaffoldProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SearchBarProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SegmentedButtonProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SegmentedButtonRowProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SliderProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SnackbarHostProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SpacerProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SurfaceProps): T = visitDefault(props)
    fun visit(props: NodeProperties.SwitchProps): T = visitDefault(props)
    fun visit(props: NodeProperties.TabProps): T = visitDefault(props)
    fun visit(props: NodeProperties.TabRowProps): T = visitDefault(props)
    fun visit(props: NodeProperties.TextFieldProps): T = visitDefault(props)
    fun visit(props: NodeProperties.TextProps): T = visitDefault(props)
    fun visit(props: NodeProperties.TimePickerProps): T = visitDefault(props)
    fun visit(props: NodeProperties.TopAppBarProps): T = visitDefault(props)
    fun visitDefault(props: NodeProperties): T
}

fun <T> NodeProperties.accept(visitor: NodePropertiesVisitor<T>): T = when (this) {
        is NodeProperties.AlertDialogProps -> visitor.visit(this)
        is NodeProperties.BadgeProps -> visitor.visit(this)
        is NodeProperties.BadgedBoxProps -> visitor.visit(this)
        is NodeProperties.BottomBarProps -> visitor.visit(this)
        is NodeProperties.BottomNavigationItemProps -> visitor.visit(this)
        is NodeProperties.BoxProps -> visitor.visit(this)
        is NodeProperties.ButtonProps -> visitor.visit(this)
        is NodeProperties.CardProps -> visitor.visit(this)
        is NodeProperties.CheckboxProps -> visitor.visit(this)
        is NodeProperties.ChipProps -> visitor.visit(this)
        is NodeProperties.ColumnProps -> visitor.visit(this)
        is NodeProperties.CustomProps -> visitor.visit(this)
        is NodeProperties.DatePickerProps -> visitor.visit(this)
        is NodeProperties.DividerProps -> visitor.visit(this)
        is NodeProperties.ExtendedFabProps -> visitor.visit(this)
        is NodeProperties.FabProps -> visitor.visit(this)
        is NodeProperties.FilterChipProps -> visitor.visit(this)
        is NodeProperties.FlowColumnProps -> visitor.visit(this)
        is NodeProperties.FlowRowProps -> visitor.visit(this)
        is NodeProperties.IconProps -> visitor.visit(this)
        is NodeProperties.ImageProps -> visitor.visit(this)
        is NodeProperties.InputChipProps -> visitor.visit(this)
        is NodeProperties.ListItemProps -> visitor.visit(this)
        is NodeProperties.ModalBottomSheetProps -> visitor.visit(this)
        is NodeProperties.NavigationBarItemProps -> visitor.visit(this)
        is NodeProperties.NavigationBarProps -> visitor.visit(this)
        is NodeProperties.NavigationDrawerItemProps -> visitor.visit(this)
        is NodeProperties.NavigationDrawerProps -> visitor.visit(this)
        is NodeProperties.NavigationRailItemProps -> visitor.visit(this)
        is NodeProperties.NavigationRailProps -> visitor.visit(this)
        is NodeProperties.OutlinedCardProps -> visitor.visit(this)
        is NodeProperties.PagerProps -> visitor.visit(this)
        is NodeProperties.PlainTooltipProps -> visitor.visit(this)
        is NodeProperties.ProgressIndicatorProps -> visitor.visit(this)
        is NodeProperties.RadioButtonProps -> visitor.visit(this)
        is NodeProperties.RichTooltipProps -> visitor.visit(this)
        is NodeProperties.RowProps -> visitor.visit(this)
        is NodeProperties.ScaffoldProps -> visitor.visit(this)
        is NodeProperties.SearchBarProps -> visitor.visit(this)
        is NodeProperties.SegmentedButtonProps -> visitor.visit(this)
        is NodeProperties.SegmentedButtonRowProps -> visitor.visit(this)
        is NodeProperties.SliderProps -> visitor.visit(this)
        is NodeProperties.SnackbarHostProps -> visitor.visit(this)
        is NodeProperties.SpacerProps -> visitor.visit(this)
        is NodeProperties.SurfaceProps -> visitor.visit(this)
        is NodeProperties.SwitchProps -> visitor.visit(this)
        is NodeProperties.TabProps -> visitor.visit(this)
        is NodeProperties.TabRowProps -> visitor.visit(this)
        is NodeProperties.TextFieldProps -> visitor.visit(this)
        is NodeProperties.TextProps -> visitor.visit(this)
        is NodeProperties.TimePickerProps -> visitor.visit(this)
        is NodeProperties.TopAppBarProps -> visitor.visit(this)
}
