Feature: AI Layout Generation from Prompts
  As a composy editor user
  I want to describe a layout in natural language and have the AI generate it
  To create interfaces quickly without building the tree node by node

  Scenario: Generate simple layout from text prompt
    Given the user opens the chat panel in composy
    When they write "Create a login form with email, password, and submit button"
    Then the AI generates a component tree with Column > [TextField(email), TextField(password), Button > Text("Submit")]
    And the tree loads automatically in the editor
    And the preview shows the generated form

  Scenario: Generate complex layout from detailed prompt
    Given the user opens the chat panel
    When they write "A profile screen with circular image on top, name and bio in the center, and 3 buttons in a row at the bottom"
    Then the AI generates a tree with Scaffold > Column > [Image(circular), Text(name), Text(bio), Row > [Button, Button, Button]]
    And appropriate modifiers are applied (circular clip for image, padding, alignment)

  Scenario: Refine generated layout with additional prompt
    Given a tree generated by AI with a basic form
    When the user writes "Add a 'Welcome' title above the form"
    Then the AI modifies the existing tree adding Text("Welcome") as the first child
    And the editor tree updates

  Scenario: AI respects components available in json-to-compose
    Given the user writes "Create a video player with controls"
    When the AI processes the prompt
    Then the AI indicates that VideoPlayer is not available as a native component
    And suggests using Custom component with customType = "VideoPlayer"
    And generates the tree using Custom with appropriate data

  Scenario: AI generates valid JSON consumable by the library
    Given a layout generated by AI
    When the JSON is exported and loaded in an app with json-to-compose
    Then the app renders the layout correctly without errors

  Scenario: Conversation history with AI
    Given the user has sent multiple prompts to the AI
    When they check the chat panel
    Then they see the entire history of prompts and responses
    And can scroll to review previous generations

  Scenario: AI suggests improvements to current layout
    Given an existing tree in the editor
    When the user writes "Suggest improvements for this layout"
    Then the AI analyzes the current tree and suggests UX improvements
    And the user can accept or reject each suggestion

  Scenario: Select AI provider
    Given the user accesses AI settings
    When they select a provider (OpenAI, Anthropic, or local)
    And configure their API key
    Then the chat uses the selected provider for generations