name: Build and Deploy Site to Netlify

on:
  push:
    branches:
      - 'ignore'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build and Deploy Site
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Conveyor
        run: |
          curl -LO --insecure https://releases.hydraulic.dev/conveyor/latest/conveyor-linux-amd64
          chmod +x conveyor-linux-amd64
          sudo mv conveyor-linux-amd64 /usr/local/bin/conveyor

      - name: Build site with Conveyor
        run: conveyor make site --rerun=all

      - name: Check pwd
        run: pwd

      - name: Check ls
        run: ls

      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v3.0
        with:
          publish-dir: ./output
          production-branch: main
          deploy-message: "Deploy from GitHub Actions"
          enable-asset-optimization: true
          alias: production
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}