name: Build WASM JS Browser
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      deployments: write
    name: Build and Deploy to Cloudflare
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Cache Gradle packages and build
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
            build/  # Cache the build directory
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ hashFiles('build.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for Gradlew
        run: chmod +x ./gradlew

      - name: Build WASM JS Distribution
        run: ./gradlew :composy:wasmJsBrowserDistribution

      - name: Publish
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: composy-web-app
          directory: composy/build/dist/wasmJs/productionExecutable
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}